name: Complaint
description: File a Case Report
title: "[Complaint]: "
labels: ["complaint", "triage"]
projects: ["accountability"]
assignees:
  - MinYan10
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to complete this case report. Sunlight is the best disinfectant!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: case-type
    attributes:
      label: Case Type
      description: What category of the Foundation's administration does your case concern? Please consult the [Interchain Stiftung Guide](https://github.com/MinYan10/ICF/blob/main/stiftung/guide.md), or documentation in the [Accountability Folder](https://github.com/MinYan10/ICF/tree/main/accountability) if you are unsure. 
      options:
        - civil tort
        - criminal
        - unethical
        - grievance
        - whistleblowing
        - not illegal; but of "immoral character"
        - other
      default: 0
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other 
      description: Please describe
      placeholder: None of the above options apply, this case matter is uniquely pertains to... 
      value: "This case matter is regarding..."
  - type: dropdown
    id: offense-area
    attributes:
      label: Offense
      description: Please select the offense your case matter concerns.
      options:
        - mismanagement
        - misconduct (e.g., verbal, emotional abuse, favourtism)
        - gross misconduct (e.g., self-dealing, bribery, cronyism)
        - negligence/gross-negligence
        - fraud (e.g., tax fraud, procurement fraud)
        - theft (e.g., misappropriation of funds)
        - illicit enrichment 
        - unjust enrichment
        - money laundering
        - tortious interference
        - obfuscation or falsification 
        - misrepresentation
        - conspiracy
        - other
        - multiple
      default: 0
    validations:
      required: true
  - type: textarea
    id: other-1
    attributes:
      label: Other 
      description: Please describe the unethical, immoral or illegal activity, briefly (1-3 sentences) 
      placeholder: This is regarding management styles that may constitute misconduct...(*for example*) 
      value: "This case matter is regarding..."
  - type: dropdown
    id: who
    attributes:
      label: Who is responsible?
      description: If this is a legal proceeding, who is the defendant 
      options: 
        - Foundation Council (Ethan Buchman, Brian Crain, Fernando Pedrone)
        - Former Foundation Council members
        - Interchain AG Executive Management team members
        - Interchain Foundation employees
        - IFC stakeholder or beneficiary (e.g., core-tech contributors or teams)
        - multiple
        - other
      default: 0
    validations:
      required: true
  - type: textarea
    id: other-2
    attributes:
      label: It's complicated... 
      description: Please describe who is involved if none of the above apply. 
      placeholder: This complaint involves multiple ecosystems
      value: "This matter involves the Interchain Foundation and the *x* Foundation..."
  - type: textarea
    id: what-happened
    attributes:
      label: Complaint/Case summary
      description: Describe your case in detail. Provide any key names with contact information, a timeline of what happened and when and where it occured, and any other information you wish to provide. Attach any files or documents relevant to your case submission. If necessary, create a PR with your issue or case number, and attach supporting documents accordingly. If you have previously informed members or leadership of the Interchain Foundation regarding the case matter of your complaint, please include with whom you have been in contact, what was shared, and what was communicated to you.     
      placeholder: Tell us what happened...what is wrong. 
      value: "I have proof of fraud and misconduct. I am enclosing here a summary, timeline and supporting materials as documentation for my complaint..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and conditions
      description: By submitting this issue, I hereby declare that the statements made are true to the best of my knowledge and belief. I have verified any and all supporting materials for precision prior to submitting the information. I understand my statements and supporting documents may be quoted or published in another public forum and or medium. I understand that by sharing my materials and statements in this public forum, any user or administrator of the repository may, in their discretion, share and or reference the information provided by me with a relevant supervisory authority.   
      options:
        - label: I agree to above terms and conditions.
          required: true
